### ISSUE TITLE
执行过程中,头几行日志中 总会有"读取文件错误".

### ISSUE THREAD

**Issue by Archer456** [284772894/monkeyTest#10]
执行日志,头几行总是有 读取文件错误  且会影响到最终生成的report.xlsx 记录.

---------------------------
adb port has been released!
---------------------------
* server not running *
adb devices
adb -s 45806625 shell wm size
adb -s 45806625 shell cat /proc/meminfo
adb -s 45806625 shell cat /system/build.prop
adb -s 45806625 shell cat /proc/cpuinfo
创建文件成功
创建文件成功
创建文件成功
创建文件成功
创建文件成功
创建文件成功
创建文件成功
------writeSum-------
1
adb -s 45806625 shell monkey -p com.huasheng.stock --throttle 600 --ignore-timeouts --ignore-crashes   --monitor-native-crashes -v -v -v 600 >>D:\workspace\git\monkeyTest\log\52c2b8ba-892a-4034-ac37-4b633e9f6c07monkey.log
----get_pid-------
adb -s 45806625 shell ps | findstr com.huasheng.stock
adb -s 45806625 shell cat /proc/cpuinfo
adb -s 45806625 shell dumpsys battery
Current.Battery.Service.state:.AC.powered:.false.USB.powered:.true.Wireless.powered:.false.Max.charging.current:.0.Max.charging.voltage:.0.Charge.counter:.0.status:.2.health:.2.present:.true.level:.96.scale:.100.voltage:.4322.temperature:.330.technology:.Li-poly
读取文件错误
------read-------
D:\workspace\git\monkeyTest\info\45806625_battery.pickle
[]
------writeInfo-------
[96]
adb -s 45806625 shell cat /proc/8539/stat
utime=168
stime=64
cutime=1
cstime=0
processCpuTime=233
adb -s 45806625 shell cat /proc/8539/stat
utime=178
stime=65
cutime=1
cstime=0
processCpuTime=244
adb -s 45806625 shell cat /proc/stat
user=308300
nice=30451
system=198390
idle=1759986
iowait=5900
irq=22627
softirq=36061
totalCpuTime2361715
adb -s 45806625 shell cat /proc/stat
user=308339
nice=30465
system=198422
idle=1760775
iowait=5902
irq=22637
softirq=36063
totalCpuTime2362603
totalCpuTime3=7104
processCpuTime3=11
读取文件错误
------read-------
D:\workspace\git\monkeyTest\info\45806625_cpu.pickle
[]
------writeInfo-------
[0.15484234234234234]
--------cpu--------
0.15484234234234234
adb -s 45806625 shell  dumpsys  meminfo com.huasheng.stock
Applications.Memory.Usage.(in.Kilobytes):.Uptime:.8764865.Realtime:.10567255.**.MEMINFO.in.pid.8539.[com.huasheng.stock].**.Pss.Private.Private.SwapPss.Heap.Heap.Heap.Total.Dirty.Clean.Dirty.Size.Alloc.Free.------.------.------.------.------.------.------.Native.Heap.20059.19992.0.0.36864.25456.11407.Dalvik.Heap.29678.29492.0.0.43266.26882.16384.Dalvik.Other.3464.3460.0.0.Stack.68.68.0.0.Ashmem.2.0.0.0.Gfx.dev.15404.15404.0.0.Other.dev.12.0.12.0..so.mmap.1798.164.444.0..jar.mmap.16.8.8.0..apk.mmap.793.0.424.0..ttf.mmap.147.0.12.0..dex.mmap.310.24.156.0..oat.mmap.32894.11472.17292.0..art.mmap.2937.2624.44.0.Other.mmap.26.4.0.0.EGL.mtrack.27529.27529.0.0.GL.mtrack.4848.4848.0.0.Unknown.4366.4364.0.0.TOTAL.144351.119453.18392.0.80130.52338.27791.App.Summary.Pss(KB).------.Java.Heap:.32160.Native.Heap:.19992.Code:.30004.Stack:.68.Graphics:.47781.Private.Other:.7840.System:.6506.TOTAL:.144351.TOTAL.SWAP.PSS:.0.Objects.Views:.322.ViewRootImpl:.1.AppContexts:.5.Activities:.2.Assets:.10.AssetManagers:.2.Local.Binders:.24.Proxy.Binders:.26.Parcel.memory:.15.Parcel.count:.60.Death.Recipients:.2.OpenSSL.Sockets:.20.WebViews:.0.SQL.MEMORY_USED:.585.PAGECACHE_OVERFLOW:.392.MALLOC_SIZE:.62.DATABASES.pgsz.dbsz.Lookaside(b).cache.Dbname.4.324.94.100/31/13./data/user/0/com.huasheng.stock/databases/beacon_db.4.3744.12.0/15/1./data/user/0/com.huasheng.stock/databases/hua-sheng.Asset.Allocations.zip:/data/app/com.huasheng.stock-1/base.apk:/assets/fonts/DINPro-Black.otf:.87K.zip:/data/app/com.huasheng.stock-1/base.apk:/assets/fonts/DINPro-Bold.otf:.88K.zip:/data/app/com.huasheng.stock-1/base.apk:/assets/fonts/DINPro-Light.otf:.86K.zip:/data/app/com.huasheng.stock-1/base.apk:/assets/fonts/DINPro-Medium.otf:.87K.zip:/data/app/com.huasheng.stock-1/base.apk:/assets/fonts/DINPro-Regular.otf:.85K
读取文件错误
------read-------
D:\workspace\git\monkeyTest\info\45806625_men.pickle
[]
------writeInfo-------
[144351]
adb -s 45806625 shell dumpsys gfxinfo com.huasheng.stock
读取文件错误
------read-------
D:\workspace\git\monkeyTest\info\45806625_fps.pickle
[]
------writeInfo-------
[60]
-----fps------
60
adb -s 45806625 shell cat /proc/8539/net/dev
------flow---------
11010034
---data-----
上行流量=11010034
下行流量=3294876
读取文件错误

**Comment by Louis-me** [comment]
这是打印的log信息，应该不受影响，还有fps一直60是你的手机设置没有打开：打开开发者里面的GPU呈现模式分析-在adb shell dumpsys gcxinfo中

**Comment by Archer456** [comment]
@Louis-me   更新了下你的源码工程,读取文件错误好了. 
也打开开发者里面的GPU呈现模式分析-在adb shell dumpsys gcxinfo中 了
但是结果文件report里  fps 仍旧是60
![image](https://user-images.githubusercontent.com/18392901/35837812-2ec095d6-0b23-11e8-84e1-b672df1b383e.png)

**Comment by Archer456** [comment]
另 Analysis 里 只有汇总表格,也未见
cpu(%)    men(M) fps battery(% )  上行流量(kB) 下行流量(KB)  这些
![image](https://user-images.githubusercontent.com/18392901/35837898-96e7de12-0b23-11e8-8827-2b20baa03684.png)
