### ISSUE TITLE
请清理干净自家运行写死的路径啊...... 太坑了....

### ISSUE THREAD

**Issue by Archer456** [284772894/monkeyTest#11]
BaseMonitor.py
if __name__ == '__main__':

    # cpu_rate("2749")
    pid = get_pid("com.jianshu.haruki", "DU2TAN15AJ049163")
    # print(pid)
    # get_flow(pid, "wifi", "DU2TAN15AJ049163")
    # get_battery("DU2TAN15AJ049163")
    # get_men("com.jianshu.haruki", "DU2TAN15AJ049163")
    # print(get_cpu_kel())
    # cpu_kel = get_cpu_kel("DU2TAN15AJ049163")
    # print(cpu_rate(pid,cpu_kel,"DU2TAN15AJ049163"))
    get_flow(pid, "gprs", "emulator-5554")
    # print(get_flow("com.jianshu.haruki", "gprs"))
    # print(get_flow("com.jianshu.haruki", "gprs"))
    # print(get_flow("com.jianshu.haruki", "gprs"))

BasePickle.py
if __name__ == "__main__":
    # readInfo(PATH("../info/DU2TAN15AJ049163_battery.pickle"))
    # readInfo(PATH("../info/emulator-5554_fps.pickle"))
    # readInfo(PATH("../info/emulator-5554_battery.pickle"))
    # readInfo(PATH("../info/emulator-5554_men.pickle"))
    # readInfo(PATH("../info/DU2TAN15AJ049163_men.pickle"))
    # readInfo(PATH("../info/emulator-5554_flow.pickle"))
    readInfo("E:\\app\\py\\monkey1\\info\\info.pickle")
    # readInfo(PATH("../info/DU2TAN15AJ049163_cpu.pickle"))

BaseReport.py
if __name__ == '__main__':

    workbook = xlsxwriter.Workbook('report.xlsx')
    info = [{'emulator-5554': {'cpu': 'E:\\app\\py\\monkey1\\info\\emulator-5554_cpu.pickle', 'battery': 'E:\\app\\py\\monkey1\\info\\emulator-5554_battery.pickle', 'men': 'E:\\app\\py\\monkey1\\info\\emulator-5554_men.pickle', 'flow': 'E:\\app\\py\\monkey1\\info\\emulator-5554_flow.pickle', 'header': {'rom': 770300, 'kel': '2核', 'monkey_log': 'E:\\app\\py\\monkey1\\log\\55dd9a83-3337-46d5-bb1f-6f64b85be7cbmonkey.log', 'beforeBattery': 99, 'pix': '1440x810', 'time': '10秒', 'afterBattery': 99, 'phone_name': 'GT-I9500_samsung_4.4', 'net': 'gprs'}, 'fps': 'E:\\app\\py\\monkey1\\info\\emulator-5554_fps.pickle'}}, {'DU2TAN15AJ049163': {'cpu': 'E:\\app\\py\\monkey1\\info\\DU2TAN15AJ049163_cpu.pickle', 'battery': 'E:\\app\\py\\monkey1\\info\\DU2TAN15AJ049163_battery.pickle', 'men': 'E:\\app\\py\\monkey1\\info\\DU2TAN15AJ049163_men.pickle', 'flow': 'E:\\app\\py\\monkey1\\info\\DU2TAN15AJ049163_flow.pickle', 'header': {'rom': 3085452, 'kel': '8核', 'monkey_log': 'E:\\app\\py\\monkey1\\log\\732ac6cd-dd84-4818-80ea-d9b5339c6774monkey.log', 'beforeBattery': 94, 'pix': '1080x1920', 'time': '15秒', 'afterBattery': 94, 'phone_name': 'H60-L02_Huawei_4.4', 'net': 'gprs'}, 'fps': 'E:\\app\\py\\monkey1\\info\\DU2TAN15AJ049163_fps.pickle'}}]

    tem = OperateReport(workbook)
    tem.monitor(info)
    tem.analysis(info)
    tem.crash()
    tem.close()
    # print(len(data["cpu"]))

这哪里叫开源啊.....

**Comment by Louis-me** [comment]
代码入口在monkeytest.py,那些是我的本地调试代码，不影响使用
