### ISSUE TITLE
adb shell dumpsys package_name这个条命令是实时的么？我的意思是不用top来获取实时数据更准确些？

### ISSUE THREAD

**Issue by guoxifeng** [284772894/monkeyTest#15]

**Comment by Louis-me** [comment]
取cpu占用情况时，不要用top和dump cpuinfo,因为他们拿到的是几个cpu的值，会出现超过100%

**Comment by Louis-me** [comment]
取cpu占用情况时，不要用top和dump cpuinfo,因为他们拿到的是几个cpu的值，会出现超过100%

**Comment by Louis-me** [comment]
取cpu占用情况时，不要用top和dump cpuinfo,因为他们拿到的是几个cpu的值，会出现超过100%

**Comment by Louis-me** [comment]
取cpu占用情况时，不要用top和dump cpuinfo,因为他们拿到的是几个cpu的值，会出现超过100%
